### ISSUE TITLE
Very messy code

### ISSUE THREAD

**Issue by codeyash** [TemoaProject/temoa#2]
https://github.com/TemoaProject/temoa/blob/energysystem/db_io/Make_Graphviz.py

It's hard to use this file. Code is not using any OOPs at all. 

No way to call functions directly from any other python code.

Please use Design patterns + OOP . Divide code logic into multiple files.

**Comment by TemoaProject** [comment]
Ankur has completely refactored the Graphviz code as suggested.

**Comment by codeyash** [comment]
:+1:
