### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by gschivley** [TemoaProject/temoa#5]
Longer-term issue, but [most major scientific libraries are moving to require Python 3](https://python3statement.org/). Packages used in Temoa that will be dropping python 2 support include:
- IPython
- Pandas
- Matplotlib
- numpy

Looking through the codebase I noticed that cStringIO will have to be imported from io and most (but not all?) print statements will need to change. Not sure if there's anything else.

I might start trying to run with Python 3 and see what bugs come up.

**Comment by TemoaProject** [comment]
Thanks for the heads up -- we agree this is an issue. For a long time, Pyomo relied on Python 2.7, and so that's what we've used. We'll investigate further, probably later in the spring. If you run and uncover other issues under Python 3, please let us know.

**Comment by gschivley** [comment]
I’ve [started a branch](https://github.com/gschivley/temoa/tree/energysystem-python3) where I’ll be running Python 3. So far it’s just been 

```py
try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschivley** [comment]
Some other comments.

- I might try running [futurize](https://python-future.org/futurize.html) to automate conversion.
- Temoa documentation says to use tabs in some instances. Python 3 won't allow a combination of tabs and spaces.

I'm running into unrelated issues (see #6) that have kept me from running code with Python 2 or 3.

**Comment by TemoaProject** [comment]
Temoa has now been ported to Python 3. Thanks @gschivley for the help!
