### ISSUE TITLE
Installation instructions & solver

### ISSUE THREAD

**Issue by AaronHolm** [TemoaProject/temoa#8]
I'm having trouble getting the installation up and running:

1) I'd suggest updating the language from "conda env create" to "conda env create -f environment.yml" as the former didn't install from the file, but did create an empty environment.

2) Coincbc and glpk=4.59 both caused problems for creating the environment. I'm using Windows and will try switching to a Linux version as it looks like coincbc does not have a Windows version, but I'm also struggling to find glpk=4.59 on anaconda.org, but I do find 4.57 or 4.65 versions.

**Comment by TemoaProject** [comment]
Thanks for pointing out these issues.

1. I've successfully created the Temoa environment under MacOS and Windows using "conda env create" and it seems to work fine, so I left it.
2. I investigated GLPK some more, and it looks like the latest version (v4.65) works fine with Temoa, so I removed the version number requirement in the environment.yml file. I also updated the README to warn Windows users that coincbc is not available for Windows.
